resources:
  - name: concourse-build
    type: git
    icon: github
    source:
      uri: https://github.com/neelabh0905/concourse-ci.git
      branch: master

  - name: image-build
    type: docker-image
    icon: docker
    source:
      repository: neelabh24/mvnimg
      username: ((registry-username))
      password: ((registry-password))

jobs:
  - name: build-test
    plan:
      - get: concourse-build
        trigger: true
      - task: mvn-test
        file: "concourse-build/maven-test.yml"

  - name: docker-image-build
    serial: true
    plan:
      - get: concourse-build
        trigger: true
      - task: mvn-package
        file: "concourse-build/maven-package.yml"
      - put : image-build
        params:
          build: concourse-build-out
